# Generated by Django 3.1.7 on 2022-05-03 15:47

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('text_small', models.CharField(blank=True, max_length=255, null=True, verbose_name='Texto pequeño')),
                ('descripcion', ckeditor.fields.RichTextField(verbose_name='Descripción')),
                ('active', models.BooleanField(default=False, verbose_name='Destacado')),
                ('image', models.ImageField(null=True, upload_to='static/upload', verbose_name='Imagen Principal')),
            ],
            options={
                'verbose_name_plural': 'B. Blog',
            },
        ),
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('name', models.CharField(help_text='Nombre del negocio', max_length=255, verbose_name='Nombre')),
                ('slogan_1', models.CharField(blank=True, help_text='Primer texto en la imagen del banner en la Página de inicio', max_length=255, null=True, verbose_name='Texto del Banner Inicio 1')),
                ('slogan_2', models.CharField(blank=True, help_text='Segundo texto en la imagen del banner de inicio', max_length=255, null=True, verbose_name='Texto del Banner Inicio 2')),
                ('slogan_3', models.CharField(blank=True, help_text='Tercer Texto en la imagen del banner de inicio', max_length=255, null=True, verbose_name='Texto del Banner Inicio 3')),
                ('text_1_solicitud', models.CharField(blank=True, help_text='1er texto del Cartel arriba del formulario', max_length=255, null=True, verbose_name='Primer texto de formulario solicitud')),
                ('text_2_solicitud', models.CharField(blank=True, help_text='2do texto del Cartel arriba del formulario', max_length=255, null=True, verbose_name='Segundo texto de formulario solicitud')),
                ('text_3_solicitud', models.CharField(blank=True, help_text='3er texto del Cartel arriba del formulario', max_length=255, null=True, verbose_name='Tercer texto de formulario solicitud')),
                ('text_portafolio_inicio', models.CharField(blank=True, help_text='Texto que encabeza el portafolio en inicio', max_length=255, null=True, verbose_name='Texto que encabeza el portafolio')),
                ('image_banner_1', models.ImageField(help_text='Imagen del Banner en la Página de inicio', upload_to='static/upload', verbose_name='Imagen Banner Inicio')),
                ('text_1_about', models.CharField(blank=True, help_text='Titulo de la página Nosotros', max_length=255, null=True, verbose_name='Titulo de Contactos')),
                ('descripcion_about', ckeditor.fields.RichTextField(help_text='Descripción de la Página Nosotros', verbose_name='Descripcion de Nosotros')),
                ('image_about', models.ImageField(help_text='Imagen de la página Nosotros', upload_to='static/upload', verbose_name='Imagen de nosotros')),
                ('image_banner_2', models.ImageField(help_text='Imagen del Banner en el resto de las vistas', upload_to='static/upload', verbose_name='Imagen Banner Otras Vistas')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Direccion')),
                ('horario', models.CharField(blank=True, help_text='Horarios', max_length=255, null=True, verbose_name='Horarios')),
                ('email', models.EmailField(blank=True, help_text='Correo que aparece en la página contactos', max_length=254, null=True, verbose_name='Correo de Contactos')),
                ('map_addres', models.TextField(help_text='Mapa de la ubicación del negocio', verbose_name='Direccion google maps, src')),
                ('phone', models.CharField(max_length=255, verbose_name='Telefono')),
                ('face', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('inst', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('twit', models.URLField(blank=True, null=True, verbose_name='Twitter')),
                ('yout', models.URLField(blank=True, null=True, verbose_name='YouTube')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Linkedin')),
            ],
            options={
                'verbose_name_plural': 'A. General',
            },
        ),
        migrations.CreateModel(
            name='Info_extra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('cantidad', models.IntegerField(blank=True, null=True, verbose_name='Cantidad')),
                ('image', models.ImageField(null=True, upload_to='static/upload', verbose_name='Logo')),
            ],
            options={
                'verbose_name_plural': 'D. Información Extra',
            },
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('name', models.CharField(max_length=255, verbose_name='Tipo de Moneda')),
            ],
            options={
                'verbose_name_plural': 'F. Tipos de Monedas',
            },
        ),
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre Completo')),
                ('text', models.TextField(verbose_name='Texto')),
            ],
            options={
                'verbose_name_plural': 'M. Opiniones',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del servicio')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Texto')),
                ('image', models.ImageField(null=True, upload_to='static/upload', verbose_name='Imagen')),
            ],
            options={
                'verbose_name_plural': 'K. Servicios',
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('phone', models.CharField(default='', max_length=255, verbose_name='Teléfono')),
                ('full_name', models.CharField(max_length=255, verbose_name='Nombre Completo')),
                ('tipo_servicio', models.CharField(max_length=255, verbose_name='Tipo de Servicio')),
                ('text', models.TextField(verbose_name='Mensaje')),
            ],
            options={
                'verbose_name_plural': 'J. Solicitudes',
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('image', models.ImageField(null=True, upload_to='static/upload', verbose_name='Logo')),
            ],
            options={
                'verbose_name_plural': 'E. Patrocinadores',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre Completo')),
                ('ocupation', models.CharField(max_length=255, verbose_name='Ocupación')),
                ('image', models.ImageField(null=True, upload_to='static/upload', verbose_name='Imagen')),
                ('face', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('inst', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('twit', models.URLField(blank=True, null=True, verbose_name='Twitter')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Linkedin')),
            ],
            options={
                'verbose_name_plural': 'L. Equipo de trabajo',
            },
        ),
        migrations.CreateModel(
            name='Tipo_galery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
            ],
            options={
                'verbose_name_plural': 'H. Tipo de Galería',
            },
        ),
        migrations.CreateModel(
            name='Planes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('price', models.FloatField(default=0, verbose_name='Precio del plan')),
                ('descripcion', ckeditor.fields.RichTextField(default='', verbose_name='Descripción')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DreamApp.moneda', verbose_name='Tipo de Moneda')),
            ],
            options={
                'verbose_name_plural': 'G. Planes de boda',
            },
        ),
        migrations.CreateModel(
            name='Galery_blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('image', models.ImageField(null=True, upload_to='static/upload', verbose_name='Imagen')),
                ('blog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DreamApp.blog', verbose_name='Blog')),
            ],
            options={
                'verbose_name_plural': 'C. Galería del Blog',
            },
        ),
        migrations.CreateModel(
            name='Galery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('text', models.CharField(max_length=255, verbose_name='Texto')),
                ('image', models.ImageField(null=True, upload_to='static/upload', verbose_name='Imagen')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DreamApp.tipo_galery', verbose_name='Tipo de Galería')),
            ],
            options={
                'verbose_name_plural': 'I. Galería',
            },
        ),
    ]
