# Generated by Django 3.1.7 on 2022-05-10 15:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DreamApp', '0003_auto_20220504_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='Texto'),
        ),
    ]
