# Generated by Django 3.1.7 on 2022-05-10 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DreamApp', '0004_auto_20220510_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='galery',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Visible en inicio'),
        ),
    ]
