# Generated by Django 3.1.7 on 2022-05-11 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DreamApp', '0007_auto_20220511_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='tipo_servicio',
            field=models.CharField(default=2, max_length=255, verbose_name='Tipo de Servicio'),
            preserve_default=False,
        ),
    ]
