# Generated by Django 3.1.7 on 2022-05-11 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DreamApp', '0008_auto_20220511_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='tipo_servicio',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='servicio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DreamApp.service', verbose_name='Tipo de Servicio'),
            preserve_default=False,
        ),
    ]
