# Generated by Django 3.1.7 on 2022-05-12 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DreamApp', '0010_auto_20220512_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_at',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
