# Generated by Django 3.1.7 on 2022-05-26 02:31

import ckeditor.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DreamApp', '0012_auto_20220512_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='general',
            name='policity_privacity',
            field=ckeditor.fields.RichTextField(default=1, help_text='Descripción de la Politica y la Privacidad', verbose_name='Politica y Privacidad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='general',
            name='term_use',
            field=ckeditor.fields.RichTextField(default=django.utils.timezone.now, help_text='Descripción de los terminos y Uso', verbose_name='Terminos y Uso'),
            preserve_default=False,
        ),
    ]
