# Generated by Django 3.1.7 on 2022-05-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DreamApp', '0013_auto_20220525_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo_galery',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Visible en inicio'),
        ),
    ]
