# Generated by Django 3.1.7 on 2022-06-04 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DreamApp', '0014_tipo_galery_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(null=True, upload_to='media/blog/%Y/%m/%d', verbose_name='Imagen Principal'),
        ),
        migrations.AlterField(
            model_name='galery',
            name='image',
            field=models.ImageField(null=True, upload_to='media/galery', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='galery_blog',
            name='image',
            field=models.ImageField(null=True, upload_to='media/galery_blog', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='general',
            name='image_about',
            field=models.ImageField(help_text='Imagen de la página Nosotros', upload_to='media/general', verbose_name='Imagen de nosotros'),
        ),
        migrations.AlterField(
            model_name='general',
            name='image_banner_1',
            field=models.ImageField(help_text='Imagen del Banner en la Página de inicio', upload_to='media/general', verbose_name='Imagen Banner Inicio'),
        ),
        migrations.AlterField(
            model_name='general',
            name='image_banner_2',
            field=models.ImageField(help_text='Imagen del Banner en el resto de las vistas', upload_to='media/general', verbose_name='Imagen Banner Otras Vistas'),
        ),
        migrations.AlterField(
            model_name='info_extra',
            name='image',
            field=models.ImageField(null=True, upload_to='media/info_extra', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(null=True, upload_to='media/service', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='image',
            field=models.ImageField(null=True, upload_to='media/sponsor', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(null=True, upload_to='media/team', verbose_name='Imagen'),
        ),
    ]
