# Generated by Django 3.1.7 on 2022-06-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DreamApp', '0015_auto_20220603_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(null=True, upload_to='blog/%Y/%m/%d', verbose_name='Imagen Principal'),
        ),
        migrations.AlterField(
            model_name='galery',
            name='image',
            field=models.ImageField(null=True, upload_to='galery', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='galery_blog',
            name='image',
            field=models.ImageField(null=True, upload_to='galery_blog', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='general',
            name='image_about',
            field=models.ImageField(help_text='Imagen de la página Nosotros', upload_to='general', verbose_name='Imagen de nosotros'),
        ),
        migrations.AlterField(
            model_name='general',
            name='image_banner_1',
            field=models.ImageField(help_text='Imagen del Banner en la Página de inicio', upload_to='general', verbose_name='Imagen Banner Inicio'),
        ),
        migrations.AlterField(
            model_name='general',
            name='image_banner_2',
            field=models.ImageField(help_text='Imagen del Banner en el resto de las vistas', upload_to='general', verbose_name='Imagen Banner Otras Vistas'),
        ),
        migrations.AlterField(
            model_name='info_extra',
            name='image',
            field=models.ImageField(null=True, upload_to='info_extra', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(null=True, upload_to='service', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='image',
            field=models.ImageField(null=True, upload_to='sponsor', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(null=True, upload_to='team', verbose_name='Imagen'),
        ),
    ]
